/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.orca.view;

import javax.swing.JDialog;

/**
 *
 * @author DCX
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCitat = new javax.swing.JLabel();
        btnNoviCitat = new javax.swing.JButton();
        lblIMG = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKnjige = new javax.swing.JMenu();
        miKnjigePregled = new javax.swing.JMenuItem();
        miKnjigeNovo = new javax.swing.JMenuItem();
        menuClanovi = new javax.swing.JMenu();
        miClanoviPregled = new javax.swing.JMenuItem();
        miClanoviNovo = new javax.swing.JMenuItem();
        menuZaduzenje = new javax.swing.JMenu();
        miZaduzenjaPregled = new javax.swing.JMenuItem();
        miZaduzenjaNovo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Citat dana:");

        btnNoviCitat.setText("Novi citat");

        lblIMG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIMG.setIcon(new javax.swing.ImageIcon("C:\\Users\\DCX\\Desktop\\Projekat Orca\\orcaLogo.PNG")); // NOI18N

        btnLogOut.setText("Izloguj se");

        menuKnjige.setText("Knjige");

        miKnjigePregled.setText("Pregled");
        miKnjigePregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKnjigePregledActionPerformed(evt);
            }
        });
        menuKnjige.add(miKnjigePregled);

        miKnjigeNovo.setText("Novo");
        miKnjigeNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKnjigeNovoActionPerformed(evt);
            }
        });
        menuKnjige.add(miKnjigeNovo);

        jMenuBar1.add(menuKnjige);

        menuClanovi.setText("Clanovi");

        miClanoviPregled.setText("Pregled");
        miClanoviPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClanoviPregledActionPerformed(evt);
            }
        });
        menuClanovi.add(miClanoviPregled);

        miClanoviNovo.setText("Novo");
        miClanoviNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClanoviNovoActionPerformed(evt);
            }
        });
        menuClanovi.add(miClanoviNovo);

        jMenuBar1.add(menuClanovi);

        menuZaduzenje.setText("Zaduzenja");

        miZaduzenjaPregled.setText("Pregled");
        miZaduzenjaPregled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miZaduzenjaPregledActionPerformed(evt);
            }
        });
        menuZaduzenje.add(miZaduzenjaPregled);

        miZaduzenjaNovo.setText("Novo");
        miZaduzenjaNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miZaduzenjaNovoActionPerformed(evt);
            }
        });
        menuZaduzenje.add(miZaduzenjaNovo);

        jMenuBar1.add(menuZaduzenje);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIMG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnNoviCitat))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCitat, javax.swing.GroupLayout.PREFERRED_SIZE, 874, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btnLogOut)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnNoviCitat)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCitat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miKnjigeNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKnjigeNovoActionPerformed
       JDialog ubaci = new FrmUnosKnjige(this, true);
       ubaci.setVisible(true);
    }//GEN-LAST:event_miKnjigeNovoActionPerformed

    private void miKnjigePregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKnjigePregledActionPerformed
        JDialog pregled = new FrmPregledKnjiga(this, true);
       pregled.setVisible(true);
    }//GEN-LAST:event_miKnjigePregledActionPerformed

    private void miClanoviPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClanoviPregledActionPerformed
        JDialog pregledClan = new FrmPregledClanova(this, true);
       pregledClan.setVisible(true);
    }//GEN-LAST:event_miClanoviPregledActionPerformed

    private void miClanoviNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClanoviNovoActionPerformed
       JDialog ubaciClan = new FrmUnosClana(this, true);
       ubaciClan.setVisible(true);
    }//GEN-LAST:event_miClanoviNovoActionPerformed

    private void miZaduzenjaPregledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miZaduzenjaPregledActionPerformed
       JDialog pregledZaduzenja = new FrmPregledZaduzenja(this, true);
       pregledZaduzenja.setVisible(true);
    }//GEN-LAST:event_miZaduzenjaPregledActionPerformed

    private void miZaduzenjaNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miZaduzenjaNovoActionPerformed
       JDialog ubaciZaduzenje = new FrmUnosZaduzenja(this, true);
       ubaciZaduzenje.setVisible(true);
    }//GEN-LAST:event_miZaduzenjaNovoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNoviCitat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCitat;
    private javax.swing.JLabel lblIMG;
    private javax.swing.JMenu menuClanovi;
    private javax.swing.JMenu menuKnjige;
    private javax.swing.JMenu menuZaduzenje;
    private javax.swing.JMenuItem miClanoviNovo;
    private javax.swing.JMenuItem miClanoviPregled;
    private javax.swing.JMenuItem miKnjigeNovo;
    private javax.swing.JMenuItem miKnjigePregled;
    private javax.swing.JMenuItem miZaduzenjaNovo;
    private javax.swing.JMenuItem miZaduzenjaPregled;
    // End of variables declaration//GEN-END:variables
}
