/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.orca.view;

/**
 *
 * @author DCX
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblCitat = new javax.swing.JLabel();
        btnNoviCitat = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblIMG = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuKnjige = new javax.swing.JMenu();
        miKnjigePregled = new javax.swing.JMenuItem();
        miKnjigeNovo = new javax.swing.JMenuItem();
        menuClanovi = new javax.swing.JMenu();
        miClanoviPregled = new javax.swing.JMenuItem();
        miClanoviNovo = new javax.swing.JMenuItem();
        menuZaduzenje = new javax.swing.JMenu();
        miZaduzenjaPregled = new javax.swing.JMenuItem();
        miZaduzenjaNovo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Citat dana:");

        btnNoviCitat.setText("Novi citat");

        btnLogOut.setText("Izloguj se");

        lblIMG.setIcon(new javax.swing.ImageIcon("C:\\Users\\DCX\\Desktop\\Projekat Orca\\orcaLogo.PNG")); // NOI18N

        menuKnjige.setText("Knjige");

        miKnjigePregled.setText("Pregled");
        menuKnjige.add(miKnjigePregled);

        miKnjigeNovo.setText("Novo");
        menuKnjige.add(miKnjigeNovo);

        jMenuBar1.add(menuKnjige);

        menuClanovi.setText("Clanovi");

        miClanoviPregled.setText("Pregled");
        menuClanovi.add(miClanoviPregled);

        miClanoviNovo.setText("Novo");
        menuClanovi.add(miClanoviNovo);

        jMenuBar1.add(menuClanovi);

        menuZaduzenje.setText("Zaduzenja");

        miZaduzenjaPregled.setText("Pregled");
        menuZaduzenje.add(miZaduzenjaPregled);

        miZaduzenjaNovo.setText("Novo");
        menuZaduzenje.add(miZaduzenjaNovo);

        jMenuBar1.add(menuZaduzenje);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblCitat, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNoviCitat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(lblIMG)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(lblIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCitat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnNoviCitat, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNoviCitat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblCitat;
    private javax.swing.JLabel lblIMG;
    private javax.swing.JMenu menuClanovi;
    private javax.swing.JMenu menuKnjige;
    private javax.swing.JMenu menuZaduzenje;
    private javax.swing.JMenuItem miClanoviNovo;
    private javax.swing.JMenuItem miClanoviPregled;
    private javax.swing.JMenuItem miKnjigeNovo;
    private javax.swing.JMenuItem miKnjigePregled;
    private javax.swing.JMenuItem miZaduzenjaNovo;
    private javax.swing.JMenuItem miZaduzenjaPregled;
    // End of variables declaration//GEN-END:variables
}
